services:
  matching-service:
    build: ./matching-service
    restart: always
    env_file:
      - .env
    ports:
      - 8001:8001

  db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
#    volumes:
#      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
